version: '3'
services:
    php:
        image: php:7.4-fpm
        volumes:
            - ./src:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database_voco
